### ISSUE TITLE
projects don't work

### ISSUE THREAD

**Issue by rpanjwani** [telerik/ui-for-aspnet-core-examples#1]
I downloaded and followed instructions but can't run:

`HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect`

**Comment by CecoMilchev** [comment]
Hi Riz,
The exception suggests that there has been a mismatch between the ASP.NET Core versions. Or, probably the project is built against a version which is not available on your machine. 
For instance, there are projects which are built against the ASP.NET Core 1.0 version. In case it has not been installed along with its SDK, the exception would be thrown. 

Can you ensure that the ASP.NET Core 1.0 is available on your machine? And, is the exception thrown in all of the projects or only in certain ones?
