### ISSUE TITLE
Package Reference to Trial version

### ISSUE THREAD

**Issue by bdnts** [telerik/ui-for-aspnet-core-examples#16]
In Telerik.Examples.RazorPages, by design it has a PackageReference to Telerik.UI.for.AspNet.Core.Trial  However, this won't compile for a licensed developer, and there is no mention in the documentation that this should be changed, the project then unloaded and loaded for a successful compile

**Comment by CecoMilchev** [comment]
Hi, thank you for your valuable feedback. I have added the steps needed to run the sample projects with a commercial NuGet package in the [README file](https://github.com/telerik/ui-for-aspnet-core-examples#referencing-the-commerial-nuget-package).
